/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink']
    BaseFormer: typeof import('./src/components/layout/BaseFormer.vue')['default']
    BaseMenu: typeof import('./src/components/layout/BaseMenu.vue')['default']
    BaseTable: typeof import('./src/components/layout/BaseTable.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Language: typeof import('./src/components/layout/language.vue')['default']
    Login: typeof import('./src/components/userProfile/Login.vue')['default']
    MainContainer: typeof import('./src/components/MainContainer.vue')['default']
    Register: typeof import('./src/components/userProfile/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
